Console.WriteLine("Калькулятор чаевых!");
Console.Write("Введите сумму счета (руб): ");
double bill = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите процент чаевых (например, 10): ");
double tipPercent = Convert.ToDouble(Console.ReadLine());
double tipAmount = bill * (tipPercent/100);
double totalAmount = bill + tipAmount;
Console.Write("\n Результат: ");
Console.Write($"Сумма счета: {bill} руб");
Console.Write($"Чаевые ({tipPercent}%): {tipAmount} руб");
Console.Write($"Итог к оплате: {totalAmount} руб");
Console.Write("Спасибо за использование калькулятора!");
